cache:
  paths:
    - node_modules

image: node:14

pages:
  script:
    - yarn install
    - ./node_modules/.bin/gatsby build 
  artifacts:
    paths:
      - public
  only: # Only run for these branches
    - main